require:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# Custom rules for the project
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
